name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install
        chmod +x ./node_modules/.bin/jest

    - name: Run Tests
      run: npm test

    # Only run Docker steps if tests pass and we're on main branch
    - name: Login to Docker Hub
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: vamashah11
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker image
      if: success() && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: vamashah11/node-app:latest
